#!/system/bin/sh

# we need to force the wl1251 driver to disable transmitter power
ifconfig wlan0 up
ifconfig wlan0 down
echo 0 > /sys/class/rfkill/rfkill0/state
echo 0 > /sys/class/rfkill/rfkill1/state
